### ISSUE TITLE
Logging and log submission should be explicit and require user intervention

### ISSUE THREAD

**Issue by stakats** [zotero/zotero-ios#211]
Behavior should mirror what's in the desktop app.

<img width="208" alt="Screen Shot 2021-03-10 at 1 32 32 PM" src="https://user-images.githubusercontent.com/244886/110630422-9daed600-81a5-11eb-855c-5f7e071a37d7.png">

<img width="212" alt="Screen Shot 2021-03-10 at 1 32 48 PM" src="https://user-images.githubusercontent.com/244886/110630436-a0a9c680-81a5-11eb-83e1-ac59d720159b.png">

<img width="369" alt="Screen Shot 2021-03-10 at 1 33 25 PM" src="https://user-images.githubusercontent.com/244886/110630325-8374f800-81a5-11eb-835b-4c0d9b9213fc.png">

**Comment by michalrentka** [comment]
@dstillman @stakats I noticed that some people on forums mentioned this too so I implemented something similar on iOS. I also added "Cancel Logging" so that you don't have to submit it when you don't like something. I'd probably change "Stop Logging" to something like "Submit Logs". What do you think?

![IMG_0320](https://user-images.githubusercontent.com/1022956/216591116-72e86106-a8b3-4e4a-8737-d3245b8b24e7.PNG)
![IMG_0321](https://user-images.githubusercontent.com/1022956/216591133-4b5068c8-19f3-4668-a9bb-736019127521.PNG)
