### ISSUE TITLE
Full sync capability

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#258]
The client has a concept of a "full sync", which it uses in a few rare situations, including upgrades from the previous sync system. One that's relevant to iOS is an object-level 412 — that is, if the version the app has for an object is outdated, there was some bug that let that happen, and we might be missing data, so we need to fully reconcile the two sides to be safe. We'll also need it to recover from https://github.com/zotero/zotero-ios/issues/257 for existing users.

Client code is here: https://github.com/zotero/zotero/blob/3536a384a9512671e27317b6b2867450909e1092/chrome/content/zotero/xpcom/sync/syncEngine.js#L1694

Tests are here: https://github.com/zotero/zotero/blob/3536a384a9512671e27317b6b2867450909e1092/test/tests/syncEngineTest.js#L4459

See the code for the exact process, but basically we're fetching all deletions and all object versions, without passing `?since=` for anything, and comparing to the local database. Remote deletions are re-applied, remote objects that are missing or outdated locally are downloaded, and local objects marked as synced that aren't available remotely are marked as unsynced. As with the normal sync process, if the remote library version changes during successive download requests, we delay increasing amounts of time and restart the process.

Downloading objects (`this._downloadObjects()` in the linked code) can trigger conflicts if the local version is marked as unsynced. Until we have CR, the only option would be to either have that be a download failure (added to the backoff queue) or have the remote version overwrite. We should probably go with the former for now, and we'll try to come up with a CR plan with proper field merging soon.

**Comment by michalrentka** [comment]
@dstillman so most of this is already implemented, except "local objects marked as synced that aren't available remotely are marked as unsynced" and CR handling resulting in download failure. 

I don't think that choosing download failure in case of conflict makes sense currently. It would put the item on backoff schedule as you mentioned, but we currently prefer remote changes for "normal" syncs. When the sync time comes again for this item, remote changes will just overwrite local changes anyway. We can as well do this immediately on full sync.

Another question is when/how do we trigger this sync? As discussed, we might auto trigger it on object-level 412. What about other cases?

**Comment by michalrentka** [comment]
Also it would be nice to synchronise again on how to handle sync errors in general. Currently the state of sync is:
- When sync is cancelled by user, nothing else happens.
- When sync is aborted due to fatal error, we don't retry. Exception is the object-level 412. If this fails with full sync as well, we don't retry anymore.
- When sync finished with non-fatal errors we try to retry the same sync again, if that happens we try current full sync (which we probably shouldn't do).

**Comment by dstillman** [comment]
What do you mean by "already implemented"? Do you just mean you already have the ability to make requests without `since`? Because that's certainly not the normal sync process.

> I'd add that if local objects are marked as synced, not available remotely and marked as deleted, I'd just delete it locally. Otherwise mark it as unsynced so that they'll write on next sync.

Meaning in the delete log remotely? That's already specified above — the first step in the full sync is reprocessing all remote deletions without `since`. If a remotely deleted object is marked as synced locally, it gets deleted locally, same as a normal remote deletion. If there's a remote deletion and the local object is unsynced, that's a conflict, and in lieu of CR it would be better to restore the local version.

> We currently prefer remote changes for "normal" syncs. When the sync time comes again for this item, remote changes will just overwrite local changes anyway. We can as well do this immediately on full sync.

Sure, though the problem here is that, due to #257, people could theoretically have many multiple changes in conflict, and overwriting them isn't great. Items that were just never pulled down aren't a problem, but if people were in sync, made a lot of changes to items elsewhere, and then triggered #257, any changes they then made locally to those items would be in conflict. But hopefully that's something people would generally notice, and they wouldn't start, say, editing a note without realizing that it was out of date… We can probably get away with this for the moment, but we should come up with a CR plan soon.

> Another question is when/how do we trigger this sync? As discussed, we auto trigger it on object-level 412 (we already do this with current full sync btw). What about other cases?

Because of #257, I think we'll need to trigger this automatically on upgrade for current existing users. I think that's the only other known case where this is necessary at the moment.

We'll want to make sure we have tests covering the full sync, similar to the client tests.

> When sync is aborted due to fatal error, we don't retry. Exception is the object-level 412. If this fails with full sync as well, we don't retry anymore.

Yeah, this is important. The client only tries a full sync once after an object-level 412. If a 412 happens again, the sync [fails](https://github.com/zotero/zotero/blob/3536a384a9512671e27317b6b2867450909e1092/chrome/content/zotero/xpcom/sync/syncEngine.js#L170), and the user hopefully comes and reports the sync error so we can fix whatever the underlying problem is.

In the client, a new sync then clears the flag and allows a full sync to be triggered again after another 412. That's maybe not ideal — it could make for a lot of requests for all object versions — but I'm not sure what the alternative is. Could maybe limit full-sync-on-412 to manual syncs for 1 hour or something?

> When sync finished with non-fatal errors we try to retry the same sync again, if that happens we try current full sync (which we probably shouldn't do).

What's an example of a non-fatal error? 5xx should be retried at the HTTP request level.  But yes, other than for #257, this new full sync should only happen for an object-level 412.

**Comment by michalrentka** [comment]
> What do you mean by "already implemented"? Do you just mean you already have the ability to make requests without since? Because that's certainly not the normal sync process.

Not normal sync process of course. I think when we dealt with 412 in the beginning you told me something about full sync (not the full picture as in this issue) and I implemented a version of it where everything tries to sync again while ignoring local versions. So a lot of this has already been implemented before, that's what I meant.

>> I'd add that if local objects are marked as synced, not available remotely and marked as deleted, I'd just delete it locally. Otherwise mark it as unsynced so that they'll write on next sync.
>
> Meaning in the delete log remotely?

Initially I meant when a local object which was not yet synced (so not available remotely) was skipped during sync and then deleted locally by user. I guess this scenario is not even possible.

> If there's a remote deletion and the local object is unsynced, that's a conflict, and in lieu of CR it would be better to restore the local version.
Yes, that's what we do and what I'll keep for full sync for now.

>> We currently prefer remote changes for "normal" syncs. When the sync time comes again for this item, remote changes will just overwrite local changes anyway. We can as well do this immediately on full sync.
>
> Sure, though the problem here is that, due to #257, people could theoretically have many multiple changes in conflict, and overwriting them isn't great. Items that were just never pulled down aren't a problem, but if people were in sync, made a lot of changes to items elsewhere, and then triggered #257, any changes they then made locally to those items would be in conflict. But hopefully that's something people would generally notice, and they wouldn't start, say, editing a note without realizing that it was out of date… We can probably get away with this for the moment, but we should come up with a CR plan soon.

I understand, but currently it doesn't make sense to put it on backoff, because when the backoff time expires and the item syncs again, it'll be rewritten with remote state anyway. I don't think we'll have CR ready before that backoff expires.

> In the client, a new sync then clears the flag and allows a full sync to be triggered again after another 412. That's maybe not ideal — it could make for a lot of requests for all object versions — but I'm not sure what the alternative is. Could maybe limit full-sync-on-412 to manual syncs for 1 hour or something?

This happens on iOS too currently and I was wondering about that. Time limit here is probably the only option.

>> When sync finished with non-fatal errors we try to retry the same sync again, if that happens we try current full sync (which we probably shouldn't do).
>
> What's an example of a non-fatal error? 5xx should be retried at the HTTP request level. But yes, other than for #257, this new full sync should only happen for an object-level 412.

I'm looking at non fatals and currently it's version mismatch (remote version increased during sync), schema (missing field, item type) and parsing errors. Schema and parsing errors don't really make sense. Version mismatch removes sync for current library and continues with other libraries and at the end issues a retry sync for the mismatched library. So I'll change it to retry only for version mismatch, otherwise it doesn't really make sense.

**Comment by michalrentka** [comment]
@dstillman we should probably ask the user whether he/she wants to start a full sync instead of just starting it the first time after update. It might take long time and if the user just quickly wants to check something, the full sync will be cancelled. It's not necessarily terrible, but it would be best to just let it run and not keep cancelling it.

**Comment by dstillman** [comment]
No, users shouldn't need to know about this, or understand what it means — we're just correcting a problem that shouldn't have happened.

And it shouldn't really take a long time. It's all just based on the `format=versions` requests. In most cases there wouldn't even be any differences and nothing would happen beyond those requests.
