### ISSUE TITLE
Embedded newlines in highlight text

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#308]
It seems like we're including newlines in extracted text on iOS, which doesn't happen on desktop. @mrtcode can comment on our approach there — not sure if we get that for free from pdf.js or we're doing something special there.

![IMG_0035](https://user-images.githubusercontent.com/783082/122610427-9ffab900-d04d-11eb-84de-8615e5b38be9.PNG)

**Comment by mrtcode** [comment]
Currently we don't use any PDF.js logic to extract text because it's inferior. Instead, we only pull characters data from PDF.js that includes position, font, etc. and process it with another logic that is ported from Xpdf `pdftotext` which allows to get words from characters. There is a plan to port the logic that makes lines from words and paragraphs from lines. For lines extraction we are currently using our own logic.

Speaking about new lines, we're currently just checking if the last character in the line [has dash](https://github.com/zotero/pdf-reader/blob/6a126b1cd0a67c0c25565bed2dd2621c6e29489f/src/lib/text/range.js#L4) or not, and removing it if so. I don't remember if Xpdf is doing anything more intelligent here or not, but I'll investigate when I'll get back to this. Of course the result is not always correct, especially for scanned papers.

Also, I would expect PSPDFKit to be more intelligent here, maybe it allows to configure text extraction?

**Comment by michalrentka** [comment]
@dstillman can you share the pdf?

**Comment by dstillman** [comment]
Shared (though I would imagine it happens for any PDF with columns)

**Comment by michalrentka** [comment]
So the PSPDFKit implementation just adds a \r\n to the end of each line. I could remove all newline characters but then we'd loose actual new lines. There's always just single \r\n even if there is a bigger gap.

**Comment by dstillman** [comment]
Probably better to strip all newlines than to have extra newlines in all highlights. I think highlights will mostly not have real newlines in them.

**Comment by michalrentka** [comment]
So i tested this a bit. The best results I observed when I replaced newlines with whitespace. I don't replace newlines if there's a "." before them. That way we get to keep newlines between paragraphs.

Before:
![before](https://user-images.githubusercontent.com/1022956/162739354-a7a1658d-bb5b-4fb0-8c6c-13e8f2fbd29c.jpeg)
After:
![after](https://user-images.githubusercontent.com/1022956/162739386-5604c1f5-d9e2-4457-ab94-3d38774c72f1.jpeg)
