### ISSUE TITLE
Select mode for annotation sidebar

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#361]
I think we need a Select button at the top of the annotation sidebar, so you can select multiple annotations and either merge them (at least for compatible annotations, like ink annotations) or delete them.

Merging would combine tags and concatenate text/comments, with two newlines between comments.

This would be particularly useful for merging ink writing that gets detected as separate annotations (even once https://github.com/zotero/zotero-ios/issues/360 is fixed).

Annotations of different types should be group-deletable but not mergeable.

**Comment by michalrentka** [comment]
I added the ability to delete multiple annotations. Merging has some questions:
- Only inking or highlights also supported? If highlights are allowed, I'd need to check for overlaps as well, because highlight annotation cannot have holes.
- I guess only the same colors should be available for merging?

**Comment by dstillman** [comment]
(Or maybe the most common thickness to start, and if there's a tie then choose the thickness of the set with the earliest annotation?)

**Comment by michalrentka** [comment]
I have implemented the requested preference for line width thickness now.
