### ISSUE TITLE
WebDAV: 404 saved as file and then reuploaded and then redownloaded incorrectly

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#378]
This is very bizarre, and maybe no longer an issue, but here's what happened:

On November 4 (so in a previous build), I was playing with WebDAV, and I tried to download a snapshot of the Zotero Forums front page that wasn't yet on the WebDAV server. I see multiple 404s in the server logs for that ZIP:

```
172.17.0.1 - test [04/Nov/2021:08:08:47 +0000] "GET /zotero/FVA9I9RE.zip HTTP/1.1" 404 217 "-" "Zotero/161 CFNetwork/1240.0.4 Darwin/20.6.0"
```

Uploading was broken because of https://github.com/zotero/zotero-ios/issues/374.

Today I updated to the latest build and reverified the server, and it started to upload local files.

When I tried to open the file, I got this:

![webdav-zip-not-found](https://user-images.githubusercontent.com/783082/140899758-9385aee6-1bff-41a0-83c0-408df5637c36.jpg)

Looking on the server, there's a 359-byte ZIP file with a forums.zotero.org.html containing this:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /zotero/FVA9I9RE.zip was not found on this server.</p>
</body></html>
```

And the webview appears to be showing the ASCII contents of the ZIP file itself, rendered as HTML.

Grepping for the above item key from today, I see this:

```
172.17.0.1 - test [09/Nov/2021:09:22:32 +0000] "GET /zotero/FVA9I9RE.prop HTTP/1.1" 404 218 "-" "Zotero/162 CFNetwork/1240.0.4 Darwin/20.6.0"
172.17.0.1 - test [09/Nov/2021:09:22:32 +0000] "PUT /zotero/FVA9I9RE.zip HTTP/1.1" 201 192 "-" "Zotero/162 CFNetwork/1240.0.4 Darwin/20.6.0"
172.17.0.1 - test [09/Nov/2021:09:22:32 +0000] "PUT /zotero/FVA9I9RE.prop HTTP/1.1" 201 193 "-" "Zotero/162 CFNetwork/1240.0.4 Darwin/20.6.0"
172.17.0.1 - - [09/Nov/2021:09:25:17 +0000] "GET /zotero/FVA9I9RE.zip HTTP/1.1" 401 381 "-" "Zotero/162 CFNetwork/1240.0.4 Darwin/20.6.0"
172.17.0.1 - test [09/Nov/2021:09:25:17 +0000] "GET /zotero/FVA9I9RE.zip HTTP/1.1" 200 359 "-" "Zotero/162 CFNetwork/1240.0.4 Darwin/20.6.0"
172.17.0.1 - - [09/Nov/2021:09:25:37 +0000] "GET /zotero/FVA9I9RE.zip HTTP/1.1" 401 381 "-" "Zotero/162 CFNetwork/1240.0.4 Darwin/20.6.0"
172.17.0.1 - test [09/Nov/2021:09:25:37 +0000] "GET /zotero/FVA9I9RE.zip HTTP/1.1" 200 359 "-" "Zotero/162 CFNetwork/1240.0.4 Darwin/20.6.0"
```

So it seems like it saved the 404 from the other day as the contents of the file (wrong), and then reuploaded it today (fine, because actually missing on WebDAV), and then redownloaded it (why, if it already thought it existed locally?) but treated the ZIP file as the underlying HTML file (yikes)?

**Comment by michalrentka** [comment]
I went through this and hopefully this should be mostly fixed.

`So it seems like it saved the 404 from the other day as the contents of the file (wrong)`
This should be fixed now.

`and then reuploaded it today (fine, because actually missing on WebDAV)`
Right

`and then redownloaded it (why, if it already thought it existed locally?)`
I check whether the file is local, but I also compare the md5 to the synced one. So of course the 404 file had different md5 than the original uploaded file and it tried to download again.

`but treated the ZIP file as the underlying HTML file (yikes)?`
There was no zip file, just the originally downloaded 404 html (which was also uploaded to WebDAV). The app was expecting a snapshot and found the html file, so it opened it in the web view.

**Comment by dstillman** [comment]
> There was no zip file, just the originally downloaded 404 html

No, this isn't correct. If you look at the webview, it's showing the ASCII contents of the ZIP of that HTML file — that's what the "PK" is. Maybe this is fixed now, but it was definitely trying to rendering a ZIP file as HTML.

**Comment by michalrentka** [comment]
That's right. So for some reason it downloaded the 404 page as a zip (I only zip files when uploading them to WebDAV, before upload and it's a temporary file). And I treated it like html because the snapshot was supposed to be a html and interestingly web kit actually rendered the zip file. Anyway this should all be resolved now, since the underlying issue is fixed - downloader shouldn't download 404 or any other error codes anymore.
