### ISSUE TITLE
PDF URL that leads to HTML page causes saves to fail

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#397]
https://forums.zotero.org/discussion/93265/ios-beta-share-from-safari-save-to-zotero-grayed-out

Separating out from https://github.com/zotero/zotero-ios/issues/395, since it shouldn't hang regardless

**Comment by dstillman** [comment]
This would explain ScienceDirect, but I'm not sure what's going on with the other examples in that thread. E.g., the Science.org one works fine in the desktop app. Debug ID from iOS is D336506371. It looks like it directly requests the real PDF and gets a 200.

**Comment by michalrentka** [comment]
Actually, the problem was that for some reason Alamofire can't read file size of given files. I observer progress instead of response of that download request, but since file size coudln't be read, the progress was always 0 and the UI never updated. As you noticed in the logs, the request actualy downloads fine. I can download both files from that discussion, so that should solve #395 as well.
