### ISSUE TITLE
Incorrect handling of 412 for file upload

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#400]
D1543243306

I'm getting "Sync failed (Remote sync in progress. Please try again in a few minutes.)", but the underlying error is a 412 for a file upload authorization request, not due to an ongoing sync elsewhere.

The debug log says `response: "No Response"`, but that shouldn't be true. It should be one of these, though I'm not sure which:

https://github.com/zotero/dataserver/blob/61f5390980854ea3293db8d8090d573d4892dd74/controllers/ItemsController.php#L829-L848

Without the request headers or response body, I'm not sure what's actually causing this. (I have switched between Zotero Storage and WebDAV, including a WebDAV server that was likely unavailable at times, for what that's worth.)

**Comment by michalrentka** [comment]
I was able to reproduce. I fixed the missing response and the response here is actually `If-None-Match: * set but file exists.` I'm checking it out.

**Comment by michalrentka** [comment]
@dstillman I was able to reproduce and fix this. Easiest way to reproduce is to upload a new file (from app or share extension) when you have WebDAV enabled and then switch back to ZFS. You'll start getting 412 (`If-None-Match: * set but file exists.`) when it tries to upload that file.

It happens because I didn't update a value in database for attachment item which was submitted to backend. This won't be happening for attachments created from now on. But if you already have the issue, the simple fix would be to edit the item which is problematic on desktop and then start the iPad app so that it syncs and updates that item with correct values. Or you can simply log out and log back in.
