### ISSUE TITLE
"Parent item [key] not found" despite parent being uploaded in same request

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#419]
https://forums.zotero.org/discussion/94283/ipados-warning-message-when-modifying-an-item

The upload shown here includes item Q4HWA9AW before the child item that references it, and nothing is being logged for that item.

Not sure if this is somehow triggering the reported problem ("This item has been changed remotely. It will now reload.").

**Comment by michalrentka** [comment]
@dstillman not sure why `Parent item Q4HWA9AW not found` was returned by backend. It seems like some object in that response returned 409 with that message: https://github.com/zotero/zotero-ios/blob/69c7b2e1953519e964814af68580e3caeadd67f7/Zotero/Controllers/Sync/SyncActions/SubmitUpdateSyncAction.swift#L120-L123

Anyway the reported issue `This item has been changed remotely. It will now reload` has been fixed in 164ec8821be6abfb89ce166e2acc19ae01d31341 before I noticed this.
