### ISSUE TITLE
Add "Download All Files" option to collection context menu

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#421]
https://forums.zotero.org/discussion/comment/398798/#Comment_398798

**Comment by michalrentka** [comment]
@dstillman we spoke about this in #291 so I closed that since it also included single download/remove functionality. Anyway I think I could add a context menu to collections list where you could long press "All Items" and tap "Download Attachments". 

If we want to keep this in items list, I'll have to add another icon to toolbar. Some of these might work:

![Screen Shot 2022-02-22 at 15 10 02](https://user-images.githubusercontent.com/1022956/155149152-32343d61-824d-4396-8245-85adce57599a.png)

**Comment by michalrentka** [comment]
@dstillman
