### ISSUE TITLE
Right-align user name in annotation popup

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#425]
Instead of centering

**Comment by michalrentka** [comment]
@dstillman I know it's like that on desktop, but I believe this was intentional on iOS. On iOS when annotation is not selected it doesn't show any buttons, when it's selected it shows "...", so the name would jump around if it was right-aligned
![IMG_0208](https://user-images.githubusercontent.com/1022956/154447890-c3e44b64-2d7c-428c-809e-9f11a3500a62.jpg)
![IMG_0207](https://user-images.githubusercontent.com/1022956/154447894-0dc3cc10-7bf9-4894-9dc7-c4d1d8b00efe.jpg)
.

**Comment by dstillman** [comment]
Ah, OK.
