### ISSUE TITLE
Add build/version number

### ISSUE THREAD

**Issue by stakats** [zotero/zotero-ios#427]
Possible location is the bottom of Preferences. Some apps do something nice here where they show the build/version and date; underneath it says, "Tap to copy."

**Comment by michalrentka** [comment]
I added version and build to settings. You can tap to copy it. I don't think date is necessary there. Since we have our own logging that logs these things, I guess this will only be used when describing some UI issue on forums.

![IMG_BEBA25E2D0B1-1](https://user-images.githubusercontent.com/1022956/155120560-09b7f65d-77ce-4653-acd7-2cc3f0b74838.jpeg)

**Comment by dstillman** [comment]
1) No punctuation in version string: `Version 1.0 Build 189`
2) Remove "Tap to copy."
3) Don't need the tap-to-copy functionality either. To the extent that this is necessary at all, people will just look at the build number.
