### ISSUE TITLE
Single-page view in landscape mode

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#429]
https://forums.zotero.org/discussion/93747/ios-beta-single-page-view-in-landscape-mode

In PDF Viewer I can set it to Page Transition: Jump, Page Mode: Single, Scroll Direction: Horizontal, Page Fitting: Fill and get what these people are asking for — the ability to view the page at a comfortable size, scroll down on the page as necessary, and swipe left to move to the next page. It's nice.

It seems like we're missing explicitly setting the page mode and page fitting — I guess we have Automatic/Adaptive for those now? I assume we could add these easily?

**Comment by michalrentka** [comment]
@dstillman yeah we're missing page mode and fitting options. They are easy to add, but I suggest we improve the settings a bit. Currently you open settings, change one option and it disappears. I suggest we build a proper popup with those options. PSPDFKit has something nice built in:
![IMG_F4948D7C2057-1](https://user-images.githubusercontent.com/1022956/156183998-cefcad48-bc61-46d3-96ce-8d938e2b3de6.jpeg)

I can't reuse it, because we want to be able to have our own options there. But I suggest I build something similar or even the same. We'll just need icons for it (or I can just use words in the meanwhile).

**Comment by dstillman** [comment]
Closed by https://github.com/zotero/zotero-ios/commit/fc1083ec60fce448388b68596f262c4758d154d3
