### ISSUE TITLE
Split old annotations that are too long

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#436]
If an object upload results in a 400 (within the overall 200 response, that is) with the error message "Annotation position is too long", run the annotation-splitting code.

**Comment by babbage** [comment]
FYI, looks like as a result of the commit above, the Zotero target (as opposed to the Zotero + PSPDFKit target) is no longer able to build. Appears that this is because the new AnnotationSplitter class is present in the build but AnnotationsConfig is excluded with `#if PDFENABLED`.

<img width="407" alt="Screenshot from Xcode showing build errors of Cannot find AnnotationsConfig in scope" src="https://user-images.githubusercontent.com/376937/226510604-49c359f1-d9bd-4c96-9bf3-859386412376.png">
