### ISSUE TITLE
Ink annotations split into many annotations

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#457]
https://forums.zotero.org/discussion/95211/inking-in-pdf-on-ipad-produces-too-many-notes

On sync?

**Comment by dstillman** [comment]
Seems like this is resolved for new annotations in 1.0.1, but after remerging annotations that were split erroneously in 1.0 they re-separate within a second or two.

**Comment by michalrentka** [comment]
Annotations that were created when this bug was in effect had their paths too big, so when you try to merge them, the `position` property becomes too big again and they just split again. It's the same as if you tried to merge annotations which were split properly. So unfortunately for annotations that were drawn with this issue you have to re-draw them.
