### ISSUE TITLE
Set minimum version to iOS 15?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#513]
iOS 15 is compatible with all devices that could run iOS 13 and 14 [1].

If there's anything in iOS 15 that we want to use, we could certainly set that as the minimum.

(iOS 16 drops support for iPhone 6S, iPhone 7, iPod Touch, iPad Air 2, and iPad Mini 4.)

[1] https://en.wikipedia.org/wiki/IOS_15#Supported_devices

**Comment by michalrentka** [comment]
I'm definitely not against dropping iOS 14, but I also don't have any particular iOS 15+ feature in mind that we might need. If @stakats agrees I can drop iOS 14 support.

**Comment by dstillman** [comment]
If we don't need it we might as well leave iOS 14 for now for people who haven't gotten around to updating. Just wanted to put it out there in case there's anything you've been waiting to use, or if you come across some API that would be handy.

**Comment by jgrisham** [comment]
There are many people using devices with iOS 14, including those who for whatever reason don’t have auto-updating enabled (such as international business travelers who don’t like surprises). _(As a purely personal example: my iPad runs iOS 15 but my iPhone SE, retained for its physical headphone jack, remains on iOS 14 simply because I haven’t had time to risk upgrading it after a bad iOS 12-13 upgrade experience the night prior to leaving for London.)_

Additionally, keep in mind that there may be many using older devices as either primary _(e.g. poorer or younger students)_ or secondary devices _(e.g. anyone else who might have one lying around)_.

----

As I recall, it is possible to target apps for a _wide_ range of iOS versions, yet still use new _(e.g. iOS 15/16)_ APIs by wrapping those pieces of code inside of a version-checking conditional statement.

----

If older versions are to be excluded, perhaps an in-app warning presented to those running iOS versions, say at least 90+ days before the change, might provide an opportunity for any _(especially less-technical users)_ affected to make their voices heard and provide better data for these kind of decisions.

**Comment by jgrisham** [comment]
Here is some [very recent data](https://mixpanel.com/trends/#report/ios_15/from_date:-70,report_unit:week,to_date:-1), from MixPanel.com:

> (Of all online iOS users), 13 out of 100 are not yet using iOS 15, and 3 of those 13 are using iOS 13 or earlier.

<details><summary>Further breakdown:</summary>

 - [iOS 14](https://mixpanel.com/trends/#report/ios_14/from_date:-70,report_unit:week,to_date:-1): 1 out of 10
 - [iOS 13](https://mixpanel.com/trends/#report/ios_13/from_date:-70,report_unit:week,to_date:-1): 1 out of 100
 - [iOS 12](https://mixpanel.com/trends/#report/ios_12/from_date:-70,report_unit:week,to_date:-1): 1.6 out of 100
 - [iOS 11](https://mixpanel.com/trends/#report/ios_11/from_date:-70,report_unit:week,to_date:-1): 1 out of 10,000
 - [iOS 10](https://mixpanel.com/trends/#report/ios_10/from_date:-70,report_unit:week,to_date:-1): 1 out of 1,000
 - [iOS 9](https://mixpanel.com/trends/#report/ios_10/from_date:-70,report_unit:week,to_date:-1): 2 out of 10,000

</details>

Given the [reported 1.8 billion active iOS devices in use in 2022](https://www.theverge.com/2022/1/28/22906071/apple-1-8-billion-active-devices-stats), that implies that **there are still well over 200 million devices not yet upgraded to iOS 15** _(including up to 360,000 still running iOS 9.x, and around 180 million still running iOS 14.x)_.

Even if those numbers were incorrect by an order of magnitude, it would still be a number in the tens of millions.

**Comment by hykilpikonna** [comment]
Please don't, I'm still using iOS 14.4 due to jailbreak compatibility, and I'm currently having a headache trying to modify the app to support iOS 14.4

**Comment by Pull256** [comment]
It is sad that my ipad(6th,2018) is running ios 14.3. But in 2022, I can only upgrade the firmware to ios 16. So if I want to use the zotero app I must upgrade my firmware to ios 16 but not ios 14.7. I think ios 16 running on the 2GB memory device may very slow.
