### ISSUE TITLE
Show multiple identifiers in vertical list in Add by Identifier

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#517]
With the current layout of the lookup dialog, it's impossible to see more than one identifier at a time, and it's tedious to scroll horizontally to see the comma-separated identifiers. This is a particularly a problem with Scan Text, where if you scan more than one identifier, you can't see it actually being added to the text field. On iPhones (where a lot of scanning will probably happen), there's also a lot of unused vertical whitespace below the current field.

We should see if there's another layout that makes more, at least when more than one identifier is added.

(The desktop app will switch to a multi-line textarea if you press Shift-Return or if you paste in multiple lines, for what it's worth.)

**Comment by michalrentka** [comment]
@dstillman I replaced the text field with text view (multiline). I tried to make it dynamically change height when text is added, which is definitely possible, but in combination with the popup window on iPad, it didn't animate properly and didn't look very good. So I just set it to static bigger size so that it's visible that you can have multiple lines and you can see more input. If you don't like it I can create a preview with dynamic height and we'll decide.
![IMG_0F5A01A50D80-1](https://user-images.githubusercontent.com/1022956/176693010-dee034d4-cdc9-4e4d-8051-0279c0003226.jpeg)

**Comment by dstillman** [comment]
Hmm, yeah, that just looks wrong. I think we'd need that whole field to be a roundrect (e.g., Signature field in Mail settings), with Scan Text on a gray background outside of it, or something like that.

**Comment by michalrentka** [comment]
@dstillman is this better? Or do I include the title in the rounded corner view too?

![IMG_EE7C0701781E-1](https://user-images.githubusercontent.com/1022956/176866129-5af83a55-d1a2-418b-9322-cef4239e8c13.jpeg)

**Comment by michalrentka** [comment]
@dstillman some more options
![A](https://user-images.githubusercontent.com/1022956/176875547-8b86f40f-da8c-4a93-beab-2fdd2819784e.jpeg)
![B](https://user-images.githubusercontent.com/1022956/176875560-6529bb6b-a39c-41ee-bc77-be7bccd6c859.jpeg)
![C](https://user-images.githubusercontent.com/1022956/176875566-43dbbd43-52c2-44b0-a98c-6b62868e7d9c.jpeg)

**Comment by dstillman** [comment]
A!
