### ISSUE TITLE
Problems saving from ScienceDirect

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#595]
https://forums.zotero.org/discussion/comment/424444/#Comment_424444

Two problems:

1) Saving from the article page — with an OA PDF — results in a permanent spinner on the child PDF for me, preventing even saving of the parent item. (I didn't check the debug output, but this seems similar to https://github.com/zotero/zotero-ios/issues/581.) We should try to fix this and also have some sort of timeout on the child PDF, so that it's always possible to save the parent item.

2) Trying to save the PDF directly — after clicking the download button on the web-based reader — tries to save a webpage item, even though seems to be an actual PDF document. Does the share extension make its own separate request for the current URL, rather than just getting the file data? Does it have a different user agent or cookie jar? I can reload the PDF in Safari and get it repeatedly, so it doesn't seem to just be a problem repeating the request.

**Comment by michalrentka** [comment]
@dstillman I'm trying to solve the second issue. I have to make a separate request there, I don't have access to safari file data directly. It had different user-agent, but even if I set user-agent and cookies to be the same, it doesn't change the behaviour. When I try to download from share extension, it's redirected to the web instead of PDF directly. I get the same PDF when I reload too, but if I leave it open for some time and reload again, it gets redirected too.

**Comment by dstillman** [comment]
Did you try Referer? I wouldn't be surprised if a Reload resends the same Referer as the original request.

**Comment by dstillman** [comment]
And for (1), that's an OA PDF, so there's some sort of problem with saving as well that we should try to fix. We don't want to just limit retries.

**Comment by michalrentka** [comment]
@dstillman adding `Referer` resolved the main issue. I made additional changes to include referer and user agent everywhere where needed and it seems to work fine now.
