### ISSUE TITLE
iPhone state restoration

### ISSUE THREAD

**Issue by michalrentka** [zotero/zotero-ios#703]
When restoring PDF state on iPhone, the collection screen appears at first, but then when you select some collection the PDF just pops up without animation. The PDF should appear immediately, I think we can select "All Items" collection in background, so that if PDF is closed the user sees all items in given library.

**Comment by dstillman** [comment]
Why can't we store the collection the user was in?

**Comment by mvasilak** [comment]
We can extend the relevant `NSUserActivity` accordingly, to include the collection in the user info.
However, we can consider making the restoration more versatile, by using the existing mechanism for custom URLs, so we can restore to whatever part of the hierarchy the user was. We can probably do this simply by building and storing the URL in the current user activity.

We may also consider app site association in the future, so that opening a web library URL in an iOS device, would do so in the app.
