### ISSUE TITLE
Login crash: "Invalid property name 'fields' for class 'RItem'"

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#769]
https://forums.zotero.org/discussion/107662/ios-error-on-login

**Comment by michalrentka** [comment]
User didn't provide more info and reinstalled the app. Unfortunately due to Xcode Cloud related issues we don't have build artifacts for 1.0.19 and can't symbolicate this crash log. So if this wasn't a random issue we'll have to wait for new reports to be able to debug it. I'm closing this ticket for now.
