### ISSUE TITLE
Redesign Copy Citation modal screen

### ISSUE THREAD

**Issue by mvasilak** [zotero/zotero-ios#830]
Look the conversation starting at https://github.com/zotero/zotero-ios/pull/827#issuecomment-1875626227 for more info.

**Comment by michalrentka** [comment]
@yexingsha so I redesigned the popup based on your design in #827. Does this look ok to you:
![IMG_3B547A9152CC-1](https://github.com/zotero/zotero-ios/assets/1022956/83b006fc-86d5-467e-a387-86a6ed76f76a)

**Comment by yexingsha** [comment]
Overall it looks fine, something nitpicky is that row height should be 44px instead of 40px. Also, I think "Preview" doesn't need to have that colon, since it's a section header, and we should use the same text style as all other section headers in the app (like all caps `footnote` in libraries screen and bold `subheadline` in item details screen, and we should make those consistent too)

**Comment by michalrentka** [comment]
@yexingsha I updated the size and section title. Section title with `subheadline`, `bold` and uppercased looks a bit excessive to me, what do you think:
![IMG_CF97034D942D-1](https://github.com/zotero/zotero-ios/assets/1022956/84963698-91db-452b-ba4f-9003acb93315)

I agree we should make section titles consistent throughout the app, but I would exclude item detail, because that screen to me looks just a bit different. Having the same small font for titles there would look weird imo. Here's how it looks now:

![IMG_1E07448B625E-1](https://github.com/zotero/zotero-ios/assets/1022956/3313f34b-4931-4f3a-90a1-1b14d83c5d38)

vs how it would look with `subheadline` `bold`:

![IMG_78CB5B4FCD72-2](https://github.com/zotero/zotero-ios/assets/1022956/00ad5ff1-791b-4975-ab17-b2a83fcf73d3)

Also we should decide whether we want to align to text (such as group libraries currently does it) or just to the left (citation popup).

**Comment by yexingsha** [comment]
The way iOS do section titles is either `footnote` `regular` uppercased (e.g. control center and most other native apps), or `subheadline` `bold` (e.g. contacts). I think we can follow that convention and use `footnote` `regular` uppercased & aligned to text for all section titles except for the item detail screen.
