### ISSUE TITLE
"Error: Unable to unzip snapshot" if file is missing on WebDAV server?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#906]
https://forums.zotero.org/discussion/comment/461279/#Comment_461279

**Comment by dstillman** [comment]
It seems like this is now being shown incorrectly when a (WebDAV?) file is missing remotely.

**Comment by dstillman** [comment]
Still not fixed, apparently:

https://forums.zotero.org/discussion/114037/ipad-still-errors-error-unable-to-unzip-snapshot-for-version-1-0-33-build-d261

**Comment by dstillman** [comment]
1.0.34 is approved but not yet released, but it wouldn't affect this, right?

**Comment by mvasilak** [comment]
1.0.34 improves on that, because it checks status codes explictly. The previous solution maintained the assumption that a WebDAV response for `404` has as content the string `Not Found` (case insensitive). Now this check happens only if we haven't decided there is an issue based on status code.

I see in the debug log that this response has `"Content-Length" : "225"`, so the previous assumption is not foolproof. Probably some server implementations return a web page instead.

Can we ask the user to test 1.0.34-263?

**Comment by dstillman** [comment]
Ah, OK. We can just release 1.0.34 tonight and ask them to test when it's live.

**Comment by dstillman** [comment]
(And yes, absolutely no reason to expect "Not Found" for a 404, and if we still have a check for that we should just take it out. The body is totally irrelevant.)

**Comment by mvasilak** [comment]
To be on the safe side then, we also need to delete the downloaded file in all cases we consider an error. We only do that now when the file is empty or `Not Found`.

**Comment by mvasilak** [comment]
I left the empty or `Not Found` check for now, as an unlikely edge case, that is always checked last. Let's see what user feedback we get first.
