### ISSUE TITLE
Auto empty trash for "My Library"

### ISSUE THREAD

**Issue by michalrentka** [zotero/zotero-ios#986]
Auto empty trashed items after 30 days

**Comment by yexingsha** [comment]
iOS native apps provide a limited number of auto-empty trash options, including "Never" so that there's no need for a separate toggle:

<img width="1112" alt="empty-trash" src="https://github.com/user-attachments/assets/ee794c7f-431d-40f2-8363-b9e5719724e0">

<img width="1112" alt="empty-trash-options" src="https://github.com/user-attachments/assets/317dae5b-1d16-47c9-97dc-459afdb64f9a">

If we want to keep the toggle + input, then the iOS convention would be to put both number and "days" at the right end of the row. Only the number is editable, with "days" acting as a unit:

<img width="1112" alt="empty-trash-textfield" src="https://github.com/user-attachments/assets/bb4932f4-8e5d-445a-b162-e115b34d2d21">

**Comment by dstillman** [comment]
Oh, yeah, separate list is fine. How about 1, 7, 14, 30, 60, Never?

**Comment by michalrentka** [comment]
@dstillman @yexingsha we can also have a popup menu instead of separate list:

![IMG_0654](https://github.com/user-attachments/assets/d3fafb04-a65c-4fef-acaf-c53a4a54d3cc)
![IMG_0655](https://github.com/user-attachments/assets/28c681ef-6de1-44a5-af3d-c9bed2de357b)

It works the same on iPhone. I can change it to separate list if you prefer that.

**Comment by yexingsha** [comment]
A popup works fine here, since there are not too many options to choose from. Though popups have a specific icon that we should use (e.g. in Settings - Account - File Syncing).
